spring:
  profiles:
#    active: EN, cat, prod
     active:
       - EN
       - cat
       - prod

ozcan:
  username: YMLUserName
  password: YMLPassword
  jdbcUrl: YMLJdbcUrl


---
spring:
  profile: prod

ozcan:
  username: YMLProdUserName
  password: YMLProdPassword
  jdbcUrl: YMLProdJdbcUrl



